### ISSUE TITLE
Commercial use/ Request limits

### ISSUE THREAD

**Issue by Tonne-TM** [hczhu/TickerTick-API#1]
I really like your API and was wondering if the API is free of use.

I couldn't find any information about commercial / non-commercial usage or request limitations. 

Could you maybe add paragraph about this to the documentation?

**Comment by hczhu** [comment]
@Tonne-TM Sorry for the late response. I added that. Let me know if you have any questions.

> The API is free of commercial/non-commercialuse use.
All endpoints have a rate limit of 6 requests per minute from the same IP. This is enforced by the service.
