### ISSUE TITLE
News data delay of about 5 hours?

### ISSUE THREAD

**Issue by Stail7** [hczhu/TickerTick-API#12]
Thank you @hczhu for your work! Can you please comment on this "issue"
While comparing to another stock news API I've found a delay of about 5 hours in timestamps.
Is it supposed to be like that or am I missing something (different timezone maybe)?

**Comment by hczhu** [comment]
@Stail7  It's by design. TickerTick news latency is a few(2-3) hours, depending on the source. Can you share the other stock news API you found?

**Comment by Stail7** [comment]
@hczhu I was having some issues with timezone but still delay is about 1 hour comparing to [https://finnhub.io/docs/api/company-news](url)
