### ISSUE TITLE
Issue with `hours_ago` and `last_id`

### ISSUE THREAD

**Issue by rjaskirat** [hczhu/TickerTick-API#13]
Hello @hczhu, thanks for your work on this API and for making it publicly available.
I have been playing with it and found an issue.
Please refer to the example provided below:

- Url `https://api.tickertick.com/feed?q=(and tt:aapl T:market)&n=2` returns the expected value:

`{'stories': [{'id': '8060448778134876128',
   'title': 'Walden Wealth Partners LLC Acquires Shares of 36,698 Apple Inc. (NASDAQ:AAPL)',
   'url': 'https://www.tickerreport.com/banking-finance/12161795/walden-wealth-partners-llc-acquires-shares-of-36698-apple-inc-nasdaqaapl.html',
   'site': 'tickerreport.com',
   'time': 1718725961000,
   'favicon_url': 'https://static.tickertick.com/website_icons/tickerreport.com.ico',
   'tags': ['aapl'],
   'description': 'Walden Wealth Partners LLC bought a new position in shares of Apple Inc. (NASDAQ:AAPL – Free Report) in the 4th quarter, according to its most recent filing with the Securities and Exchange Commission (SEC). The firm bought 36,698 shares of the iPhone maker’s stock, valued at approximately $7,065,000. Apple comprises approximately 4.4% of Walden Wealth […]',
   'tickers': ['aapl']},
  {'id': '-2915903165289240372',
   'title': 'Ables Iannone Moore & Associates Inc. Purchases Shares of 111,343 Apple Inc. (NASDAQ:AAPL)',
   'url': 'https://www.etfdailynews.com/2024/06/18/ables-iannone-moore-associates-inc-purchases-shares-of-111343-apple-inc-nasdaqaapl/',
   'site': 'etfdailynews.com',
   'time': 1718717561000,
   'favicon_url': 'https://static.tickertick.com/website_icons/etfdailynews.com.ico',
   'tags': ['aapl'],
   'description': 'Ables Iannone Moore & Associates Inc. acquired a new position in Apple Inc. (NASDAQ:AAPL – Free Report) in the fourth quarter, according to its most recent Form 13F filing with the Securities & Exchange Commission. The institutional investor acquired 111,343 shares of the iPhone maker’s stock, valued at approximately $21,437,000. Apple makes up approximately 16.4% […]',
   'tickers': ['aapl']}],
 'last_id': '-2915903165289240372'}`

### Now Adding Hours ago
- Url `https://api.tickertick.com/feed?q=(and tt:aapl T:market)&hours_ago=8760&n=2` returns an empty list

`{'stories': []}`

Edit: This query seems to be working only for `hours_ago` < 5280

### Changing the query to only selecting aapl
- Url:  `https://api.tickertick.com/feed?q=tt:aapl&hours_ago=8760&n=2` also returns the expected value

`{'stories': [{'id': '-4012295211890964378',
   'title': 'Apple Inc.: Form 4 - Statement of changes in beneficial ownership of securities',
   'url': 'https://www.sec.gov/Archives/edgar/data/320193/000032019323000070/0000320193-23-000070-index.htm',
   'site': 'sec.gov',
   'time': 1684449141000,
   'favicon_url': 'https://static.tickertick.com/website_icons/sec.gov.ico',
   'tags': ['aapl'],
   'tickers': ['aapl']},
  {'id': '7750426920303047447',
   'title': 'Apple Inc.: Form 4 - Statement of changes in beneficial ownership of securities',
   'url': 'https://www.sec.gov/Archives/edgar/data/320193/000032019323000068/0000320193-23-000068-index.htm',
   'site': 'sec.gov',
   'time': 1683930634000,
   'favicon_url': 'https://static.tickertick.com/website_icons/sec.gov.ico',
   'tags': ['aapl'],
   'similar_stories': ['-4012295211890964378'],
   'tickers': ['aapl']}],
 'last_id': '7750426920303047447'}`

## Issue with last_id

This functionality does not seem to work with hours_ago

Any support here will be appreciated.
Thank You

**Comment by hczhu** [comment]
Thanks for reporting the issue. I, actually, have deprecated `hours_ago` query parameter. If you need old stories, check out the historical data release.
https://github.com/hczhu/TickerTick-API/blob/master/README.md#historical-data
