### ISSUE TITLE
time values seems to be in accurate 

### ISSUE THREAD

**Issue by shehan011** [hczhu/TickerTick-API#2]
I have checked with several articles that the epoch time returned with an API call does not match with its article published time (which is produced with the article when I visit the url). Any reason for that ?

**Comment by Mito9999** [comment]
Are you making more than 6 requests per minute?

**Comment by shehan011** [comment]
No not at all. atm I am just going through the data to see how reliable and accurate they are and found that the two timestamps does not match.

**Comment by shehan011** [comment]
check this out 
{
      "id": "2797609833636286060",
      "title": "News Corp : and Facebook Reach Agreement in Australia",
      "url": "https://www.marketscreener.com/quote/stock/NEWS-CORPORATION-13439787/news/News-Corp-nbsp-and-Facebook-Reach-Agreement-in-Australia-32691106/?utm_medium=RSS\u0026utm_content=20210315",
      "site": "marketscreener.com",
      "time": 1615842399000,
      "favicon_url": "https://tickertick.com/website_icons/marketscreener.com.ico",
      "tags": [
        "fb"
      ]
    },
   the time here is 1615842399
   but when i visit the url and get the utc epoch it is 1615842060 there is a difference of approx 339

**Comment by shehan011** [comment]
this is another one
{
      "id": "-1032509889829059691",
      "title": "Alibaba Vs. Amazon Stock: Which Is The Better Buy | $FB $WMT $AMZN $BABA $BABAF",
      "url": "https://seekingalpha.com/article/4413411-alibaba-vs-amazon-stock-which-is-better-buy-?source=feed_tag_editors_picks",
      "site": "seekingalpha.com",
      "time": 1615570260000,
      "favicon_url": "https://tickertick.com/website_icons/seekingalpha.com.ico",
      "tags": [
        "fb"
      ]
    },
epoch returned with the api call is 1615570260
but when i visit the url and get the utc epoch it is 1615541460 (ET time converted to utc without daylight saving)

**Comment by shehan011** [comment]
Mito9999 any clue on  how to resolve my issue ?

**Comment by hczhu** [comment]
@shehan011 
It's a known issue that some story timestamps are not accurate. A timestamp can be off up to one day for a lot of stories. 
A small portion of stories may have a timestamp off dozens of days. Therefore, I'd suggest using the timestamp on the granularity of days. 
The root cause of this issue is a trade-off for less backend resource usage.

I'm curious for your use case. Do you need a highly precise publish timestamp for any article.

**Comment by hczhu** [comment]
> Are you making more than 6 requests per minute?

This inaccurate timestamp issue is irrelevant to the request rate limit.

**Comment by hczhu** [comment]
I fixed a bug which was causing the timestamp off by a few hours.
@shehan011 
I should've paid closer attention.
