### ISSUE TITLE
make watch list support more than 5 tickers.

### ISSUE THREAD

**Issue by wangyongliang** [hczhu/TickerTick-API#3]
I have added more than 5 tickers into a watchlist but only first 5 of them will be queried.

url: https://dev.tickertick.com/watchlist/7ad3b51c-bf63-4d0c-aa80-8262a7aa0420

**Comment by hczhu** [comment]
Taking a look

**Comment by hczhu** [comment]
@wangyongliang Can you try to add more tickers to the watchlist? The backend database shows the watchlist has exactly 5 tickers.

<img width="675" alt="Screen Shot 2021-06-11 at 4 28 18 PM" src="https://user-images.githubusercontent.com/2289363/121757356-23f2f500-cad2-11eb-8633-f402471de0f8.png">

**Comment by medmin** [comment]
I don't have this issue .   I have a watchlist that has 9 tickers, and all of them are in the query.

**Comment by medmin** [comment]
Besides, the watchlist belongs to you. Other people will not have a message that shows it's an invalid watchlist.
