### ISSUE TITLE
Compile a list of current API use cases

### ISSUE THREAD

**Issue by hczhu** [hczhu/TickerTick-API#4]
I'm trying to compile a list of API use cases here: https://github.com/hczhu/TickerTick-API#api-use-cases

Could you comment on this issue about your use case, if you have been using TickerTick API?

@zhangjs @xiejiahao95 @montpiere @jhaoq @ac5tin @Outsider565 @shahradelahi @Wzhishun @lastarsenal @rag71 @weilinear @shaggy63 @robinvanschaik @psyclaudeZ @gerlachjan @zrxbeijing @beyondkmp @Jack5Winnie @evanzhousy @Anchovee @matanbroner @Tonne-TM

**Comment by zhangjs** [comment]
Just interested, not used yet.

**Comment by hczhu** [comment]
> Just interested, not used yet.

Thanks for replying. Let me know if you have any question or feedback.
