### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by weilinear** [hczhu/TickerTick-API#6]
Listing some false positives I found when using the API. Will add comment when I will find more:

$FB: https://www.dailymail.co.uk/femail/article-10406125/Royal-fans-gush-Charles-Spencers-resemblance-young-Prince-Harry.html?ito=1490&ns_campaign=1490&ns_mchannel=rss&utm_campaign=TickerTick&utm_medium=website&utm_source=tickertick.com

$FB: https://www.mirror.co.uk/news/uk-news/parents-uks-biggest-family-radfords-25955913?utm_campaign=TickerTick&utm_medium=website&utm_source=tickertick.com

is it because of the `share to facebook` buttons on those webpages?

**Comment by hczhu** [comment]
Thanks for reporting false positive cases.

> is it because of the share to facebook buttons on those webpages?

Yes, exactly. It's a known problem. Any entity merely mentioned in either the title or the description will be matched to a ticker. I'm planned to use some NLU technique to extract keywords to mitigate this problem.

**Comment by hczhu** [comment]
@weilinear 
There is another term prefix `TT:` you can use to avoid such false positive cases. `TT:fb` will only match related entities with story titles.

https://api.tickertick.com/feed?q=TT:fb

**Comment by hczhu** [comment]
The quickstart section gives a request URL for better relevance.

https://github.com/hczhu/TickerTick-API#quickstart
